version: '3.7'

services:
  mysql_cloudmore:
    container_name: mysql_cloudmore
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'P_756Gt4h'
      MYSQL_DATABASE: client_service
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - crs_data:/var/lib/mysql/
  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2.8.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - ADVERTISED_HOST_NAME=localhost
    depends_on:
      - zookeeper
volumes:
  crs_data:
