version: '3.7'

services:
  app:
    image: app
    container_name: client_service
    ports:
      - "8080:8080"
    networks:
      - crs-network
    depends_on:
      - mysql_cloudmore
  mysql_cloudmore:
    container_name: mysql_cloudmore
    image: mysql:8.0
    restart: always
    networks:
      - crs-network
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'P_756Gt4h'
      MYSQL_DATABASE: client_service
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - crs_data:/var/lib/mysql/
  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - crs-network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2.8.1
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=LISTENER_BOB://kafka:9094,LISTENER_FRED://kafka:9092
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_BOB://kafka:9094,LISTENER_FRED://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_BOB
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=100

    networks:
      - crs-network
    depends_on:
      - zookeeper
volumes:
  crs_data:
networks:
  crs-network:
    driver: bridge
